/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sankuai.optaplanner.core.api.solver;
    dialect "java"

import com.sankuai.optaplanner.core.api.score.buildin.simple.SimpleScoreHolder;

import com.sankuai.optaplanner.core.impl.testdata.domain.TestdataValue;
import com.sankuai.optaplanner.core.impl.testdata.domain.TestdataEntity;

global SimpleScoreHolder scoreHolder;

// ############################################################################
// Constraints
// ############################################################################

rule "Conflict"
    when
        TestdataEntity(value != null, $leftValue : value)
        TestdataEntity(value == $leftValue)
    then
        scoreHolder.addConstraintMatch(kcontext, -1);
end
